package br.com.clinica.entity;


// Generated 26/03/2011 00:27:00 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.validator.Length;

/**
 * Especies generated by hbm2java
 */
@Entity
@Table(name = "especies", schema = "public")
public class Especies implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4633316244905154403L;
	private int codespecie;
	private String nomeespecie;
	private Set<Raca> racas = new HashSet<Raca>(0);

	public Especies() {
	}

	public Especies(int codespecie) {
		this.codespecie = codespecie;
	}

	public Especies(int codespecie, String nomeespecie, Set<Raca> racas) {
		this.codespecie = codespecie;
		this.nomeespecie = nomeespecie;
		this.racas = racas;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE,generator = "id_especie")
	@SequenceGenerator( name = "id_especie", sequenceName = "id_especie")
	@Column(name = "codespecie", unique = true, nullable = false)
	public int getCodespecie() {
		return this.codespecie;
	}
	public void setCodespecie(int codespecie) {
		this.codespecie = codespecie;
	}

	@Column(name = "nomeespecie", length = 50)
	@Length(max = 50)
	public String getNomeespecie() {
		return this.nomeespecie;
	}

	public void setNomeespecie(String nomeespecie) {
		this.nomeespecie = nomeespecie;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "especies")
	public Set<Raca> getRacas() {
		return this.racas;
	}

	public void setRacas(Set<Raca> racas) {
		this.racas = racas;
	}

}
