package br.com.clinica.entity;


// Generated 26/03/2011 00:27:00 by Hibernate Tools 3.2.4.GA

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.validator.NotNull;

/**
 * Exbiosanguinea generated by hbm2java
 */
@Entity
@Table(name = "exbiosanguinea", schema = "public")
public class Exbiosanguinea implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5691643575150342042L;
	private int codbiosanguinea;
	private Ficha ficha;
	private Date dtregistro;
	private Float albumina;
	private Float proteina;
	private Float fibrinogenio;
	private Float bilirtotal;
	private Float bilirdireta;
	private Float alt;
	private Float ast;
	private Float fosfalcalina;
	private Float ureia;
	private Float creatinina;
	private Float glicemia;
	private Float colesterol;
	private String obs;
	private Float sodio;
	private Float potassio;

	public Exbiosanguinea() {
	}

	public Exbiosanguinea(int codbiosanguinea, Ficha ficha) {
		this.codbiosanguinea = codbiosanguinea;
		this.ficha = ficha;
	}

	public Exbiosanguinea(int codbiosanguinea, Ficha ficha, Date dtregistro,
			Float albumina, Float proteina, Float fibrinogenio,
			Float bilirtotal, Float bilirdireta, Float alt, Float ast,
			Float fosfalcalina, Float ureia, Float creatinina, Float glicemia,
			Float colesterol, String obs, Float sodio, Float potassio) {
		this.codbiosanguinea = codbiosanguinea;
		this.ficha = ficha;
		this.dtregistro = dtregistro;
		this.albumina = albumina;
		this.proteina = proteina;
		this.fibrinogenio = fibrinogenio;
		this.bilirtotal = bilirtotal;
		this.bilirdireta = bilirdireta;
		this.alt = alt;
		this.ast = ast;
		this.fosfalcalina = fosfalcalina;
		this.ureia = ureia;
		this.creatinina = creatinina;
		this.glicemia = glicemia;
		this.colesterol = colesterol;
		this.obs = obs;
		this.sodio = sodio;
		this.potassio = potassio;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE,generator = "id_bio")
	@SequenceGenerator( name = "id_bio", sequenceName = "id_bio")
	@Column(name = "codbiosanguinea", unique = true, nullable = false)
	public int getCodbiosanguinea() {
		return this.codbiosanguinea;
	}

	public void setCodbiosanguinea(int codbiosanguinea) {
		this.codbiosanguinea = codbiosanguinea;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codficha", nullable = false)
	@NotNull
	public Ficha getFicha() {
		return this.ficha;
	}

	public void setFicha(Ficha ficha) {
		this.ficha = ficha;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dtregistro", length = 13)
	public Date getDtregistro() {
		return this.dtregistro;
	}

	public void setDtregistro(Date dtregistro) {
		this.dtregistro = dtregistro;
	}

	@Column(name = "albumina", precision = 8, scale = 8)
	public Float getAlbumina() {
		return this.albumina;
	}

	public void setAlbumina(Float albumina) {
		this.albumina = albumina;
	}

	@Column(name = "proteina", precision = 8, scale = 8)
	public Float getProteina() {
		return this.proteina;
	}

	public void setProteina(Float proteina) {
		this.proteina = proteina;
	}

	@Column(name = "fibrinogenio", precision = 8, scale = 8)
	public Float getFibrinogenio() {
		return this.fibrinogenio;
	}

	public void setFibrinogenio(Float fibrinogenio) {
		this.fibrinogenio = fibrinogenio;
	}

	@Column(name = "bilirtotal", precision = 8, scale = 8)
	public Float getBilirtotal() {
		return this.bilirtotal;
	}

	public void setBilirtotal(Float bilirtotal) {
		this.bilirtotal = bilirtotal;
	}

	@Column(name = "bilirdireta", precision = 8, scale = 8)
	public Float getBilirdireta() {
		return this.bilirdireta;
	}

	public void setBilirdireta(Float bilirdireta) {
		this.bilirdireta = bilirdireta;
	}

	@Column(name = "alt", precision = 8, scale = 8)
	public Float getAlt() {
		return this.alt;
	}

	public void setAlt(Float alt) {
		this.alt = alt;
	}

	@Column(name = "ast", precision = 8, scale = 8)
	public Float getAst() {
		return this.ast;
	}

	public void setAst(Float ast) {
		this.ast = ast;
	}

	@Column(name = "fosfalcalina", precision = 8, scale = 8)
	public Float getFosfalcalina() {
		return this.fosfalcalina;
	}

	public void setFosfalcalina(Float fosfalcalina) {
		this.fosfalcalina = fosfalcalina;
	}

	@Column(name = "ureia", precision = 8, scale = 8)
	public Float getUreia() {
		return this.ureia;
	}

	public void setUreia(Float ureia) {
		this.ureia = ureia;
	}

	@Column(name = "creatinina", precision = 8, scale = 8)
	public Float getCreatinina() {
		return this.creatinina;
	}

	public void setCreatinina(Float creatinina) {
		this.creatinina = creatinina;
	}

	@Column(name = "glicemia", precision = 8, scale = 8)
	public Float getGlicemia() {
		return this.glicemia;
	}

	public void setGlicemia(Float glicemia) {
		this.glicemia = glicemia;
	}

	@Column(name = "colesterol", precision = 8, scale = 8)
	public Float getColesterol() {
		return this.colesterol;
	}

	public void setColesterol(Float colesterol) {
		this.colesterol = colesterol;
	}

	@Column(name = "obs")
	public String getObs() {
		return this.obs;
	}

	public void setObs(String obs) {
		this.obs = obs;
	}

	@Column(name = "sodio", precision = 8, scale = 8)
	public Float getSodio() {
		return this.sodio;
	}

	public void setSodio(Float sodio) {
		this.sodio = sodio;
	}

	@Column(name = "potassio", precision = 8, scale = 8)
	public Float getPotassio() {
		return this.potassio;
	}

	public void setPotassio(Float potassio) {
		this.potassio = potassio;
	}

}
