package br.com.clinica.entity;

// Generated 26/03/2011 00:27:00 by Hibernate Tools 3.2.4.GA

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Exurinalise generated by hbm2java
 */
@Entity
@Table(name = "exurinalise", schema = "public")
public class Exurinalise implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1110630556163394760L;
	private int codurinalise;
	private Ficha ficha;
	private Date dtregistro;
	private String urinaColheita;
	private Float volume;
	private String aspecto;
	private String cor;
	private String odor;
	private Float densidade;
	private Float ph;
	private String proteinas;
	private String glicose;
	private String ccetonicos;
	private String bilirrubina;
	private String uribilinogenio;
	private String sgoculto;
	private String nitritos;
	private String hemacias;
	private String leucocitos;
	private String cilindros;
	private String celdescm;
	private String cristais;
	private String outros;
	private String obs;

	public Exurinalise() {
	}

	public Exurinalise(int codurinalise, Ficha ficha) {
		this.codurinalise = codurinalise;
		this.ficha = ficha;
	}

	public Exurinalise(int codurinalise, Ficha ficha, Date dtregistro,
			String urinaColheita, Float volume, String aspecto, String cor,
			String odor, Float densidade, Float ph, String proteinas,
			String glicose, String ccetonicos, String bilirrubina,
			String uribilinogenio, String sgoculto, String nitritos,
			String hemacias, String leucocitos, String cilindros,
			String celdescm, String cristais, String outros, String obs) {
		this.codurinalise = codurinalise;
		this.ficha = ficha;
		this.dtregistro = dtregistro;
		this.urinaColheita = urinaColheita;
		this.volume = volume;
		this.aspecto = aspecto;
		this.cor = cor;
		this.odor = odor;
		this.densidade = densidade;
		this.ph = ph;
		this.proteinas = proteinas;
		this.glicose = glicose;
		this.ccetonicos = ccetonicos;
		this.bilirrubina = bilirrubina;
		this.uribilinogenio = uribilinogenio;
		this.sgoculto = sgoculto;
		this.nitritos = nitritos;
		this.hemacias = hemacias;
		this.leucocitos = leucocitos;
		this.cilindros = cilindros;
		this.celdescm = celdescm;
		this.cristais = cristais;
		this.outros = outros;
		this.obs = obs;
	}
@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE,generator = "id_urina")
	@SequenceGenerator( name = "id_urina", sequenceName = "id_urina")
	@Column(name = "codurinalise", unique = true, nullable = false)
	public int getCodurinalise() {
		return this.codurinalise;
	}

	public void setCodurinalise(int codurinalise) {
		this.codurinalise = codurinalise;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codficha", nullable = false)
	@NotNull
	public Ficha getFicha() {
		return this.ficha;
	}

	public void setFicha(Ficha ficha) {
		this.ficha = ficha;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dtregistro", length = 13)
	public Date getDtregistro() {
		return this.dtregistro;
	}

	public void setDtregistro(Date dtregistro) {
		this.dtregistro = dtregistro;
	}

	@Column(name = "urina_colheita", length = 50)
	@Length(max = 50)
	public String getUrinaColheita() {
		return this.urinaColheita;
	}

	public void setUrinaColheita(String urinaColheita) {
		this.urinaColheita = urinaColheita;
	}

	@Column(name = "volume", precision = 8, scale = 8)
	public Float getVolume() {
		return this.volume;
	}

	public void setVolume(Float volume) {
		this.volume = volume;
	}

	@Column(name = "aspecto", length = 50)
	@Length(max = 50)
	public String getAspecto() {
		return this.aspecto;
	}

	public void setAspecto(String aspecto) {
		this.aspecto = aspecto;
	}

	@Column(name = "cor", length = 50)
	@Length(max = 50)
	public String getCor() {
		return this.cor;
	}

	public void setCor(String cor) {
		this.cor = cor;
	}

	@Column(name = "odor", length = 50)
	@Length(max = 50)
	public String getOdor() {
		return this.odor;
	}

	public void setOdor(String odor) {
		this.odor = odor;
	}

	@Column(name = "densidade", precision = 8, scale = 8)
	public Float getDensidade() {
		return this.densidade;
	}

	public void setDensidade(Float densidade) {
		this.densidade = densidade;
	}

	@Column(name = "ph", precision = 8, scale = 8)
	public Float getPh() {
		return this.ph;
	}

	public void setPh(Float ph) {
		this.ph = ph;
	}

	@Column(name = "proteinas", length = 50)
	@Length(max = 50)
	public String getProteinas() {
		return this.proteinas;
	}

	public void setProteinas(String proteinas) {
		this.proteinas = proteinas;
	}

	@Column(name = "glicose", length = 50)
	@Length(max = 50)
	public String getGlicose() {
		return this.glicose;
	}

	public void setGlicose(String glicose) {
		this.glicose = glicose;
	}

	@Column(name = "ccetonicos", length = 50)
	@Length(max = 50)
	public String getCcetonicos() {
		return this.ccetonicos;
	}

	public void setCcetonicos(String ccetonicos) {
		this.ccetonicos = ccetonicos;
	}

	@Column(name = "bilirrubina", length = 50)
	@Length(max = 50)
	public String getBilirrubina() {
		return this.bilirrubina;
	}

	public void setBilirrubina(String bilirrubina) {
		this.bilirrubina = bilirrubina;
	}

	@Column(name = "uribilinogenio", length = 50)
	@Length(max = 50)
	public String getUribilinogenio() {
		return this.uribilinogenio;
	}

	public void setUribilinogenio(String uribilinogenio) {
		this.uribilinogenio = uribilinogenio;
	}

	@Column(name = "sgoculto", length = 50)
	@Length(max = 50)
	public String getSgoculto() {
		return this.sgoculto;
	}

	public void setSgoculto(String sgoculto) {
		this.sgoculto = sgoculto;
	}

	@Column(name = "nitritos", length = 50)
	@Length(max = 50)
	public String getNitritos() {
		return this.nitritos;
	}

	public void setNitritos(String nitritos) {
		this.nitritos = nitritos;
	}

	@Column(name = "hemacias", length = 50)
	@Length(max = 50)
	public String getHemacias() {
		return this.hemacias;
	}

	public void setHemacias(String hemacias) {
		this.hemacias = hemacias;
	}

	@Column(name = "leucocitos", length = 50)
	@Length(max = 50)
	public String getLeucocitos() {
		return this.leucocitos;
	}

	public void setLeucocitos(String leucocitos) {
		this.leucocitos = leucocitos;
	}

	@Column(name = "cilindros", length = 50)
	@Length(max = 50)
	public String getCilindros() {
		return this.cilindros;
	}

	public void setCilindros(String cilindros) {
		this.cilindros = cilindros;
	}

	@Column(name = "celdescm", length = 50)
	@Length(max = 50)
	public String getCeldescm() {
		return this.celdescm;
	}

	public void setCeldescm(String celdescm) {
		this.celdescm = celdescm;
	}

	@Column(name = "cristais", length = 50)
	@Length(max = 50)
	public String getCristais() {
		return this.cristais;
	}

	public void setCristais(String cristais) {
		this.cristais = cristais;
	}

	@Column(name = "outros", length = 50)
	@Length(max = 50)
	public String getOutros() {
		return this.outros;
	}

	public void setOutros(String outros) {
		this.outros = outros;
	}

	@Column(name = "obs")
	public String getObs() {
		return this.obs;
	}

	public void setObs(String obs) {
		this.obs = obs;
	}

}
