package br.com.clinica.entity;

// Generated 26/03/2011 00:27:00 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Animal generated by hbm2java
 */
@Entity
@Table(name = "animal", schema = "public")
public class Animal implements java.io.Serializable {

	private static final long serialVersionUID = -5836541454202091119L;
	/**
	 * 
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "id_animal")
	@SequenceGenerator(name = "id_animal", sequenceName = "id_animal")
	@Column(name = "codanimal", unique = true, nullable = false)
	private int codanimal;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codclientes", nullable = false)
	@NotNull
	private Clientes clientes;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codraca")
	private Raca raca;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codpelagem", nullable = false)
	@NotNull
	private Pelagem pelagem;

	@Column(name = "nome", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	private String nome;

	@Temporal(TemporalType.DATE)
	@Column(name = "dtnascimento", length = 13)
	private Date dtnascimento;

	@Column(name = "sexo", nullable = false, length = 1)
	private char sexo;

	@Column(name = "cci", length = 50)
	@Length(max = 50)
	private String cci;

	@Column(name = "chip", length = 50)
	@Length(max = 50)
	private String chip;

	@Column(name = "pedigree", nullable = false)
	private boolean pedigree;

	@Column(name = "morto", nullable = false)
	private boolean morto;

	@Temporal(TemporalType.DATE)
	@Column(name = "dtmorto", length = 13)
	private Date dtmorto;

	@Column(name = "alergias", length = 50)
	@Length(max = 50)
	private String alergias;

	@Column(name = "obs")
	private String obs;

	@Column(name = "motivo", length = 30)
	@Length(max = 30)
	private String motivo;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "animal")
	private Set<Ficha> fichas = new HashSet<Ficha>(0);

	public Animal() {
	}

	public int getCodanimal() {
		return this.codanimal;
	}

	public void setCodanimal(int codanimal) {
		this.codanimal = codanimal;
	}

	public Clientes getClientes() {
		return this.clientes;
	}

	public void setClientes(Clientes clientes) {
		this.clientes = clientes;
	}

	public Raca getRaca() {
		return this.raca;
	}

	public void setRaca(Raca raca) {
		this.raca = raca;
	}

	public Pelagem getPelagem() {
		return this.pelagem;
	}

	public void setPelagem(Pelagem pelagem) {
		this.pelagem = pelagem;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public Date getDtnascimento() {
		return this.dtnascimento;
	}

	public void setDtnascimento(Date dtnascimento) {
		this.dtnascimento = dtnascimento;
	}

	public char getSexo() {
		return this.sexo;
	}

	public void setSexo(char sexo) {
		this.sexo = sexo;
	}

	public String getCci() {
		return this.cci;
	}

	public void setCci(String cci) {
		this.cci = cci;
	}

	public String getChip() {
		return this.chip;
	}

	public void setChip(String chip) {
		this.chip = chip;
	}

	public boolean isPedigree() {
		return this.pedigree;
	}

	public void setPedigree(boolean pedigree) {
		this.pedigree = pedigree;
	}

	public boolean isMorto() {
		return this.morto;
	}

	public void setMorto(boolean morto) {
		this.morto = morto;
	}

	public Date getDtmorto() {
		return this.dtmorto;
	}

	public void setDtmorto(Date dtmorto) {
		this.dtmorto = dtmorto;
	}

	public String getAlergias() {
		return this.alergias;
	}

	public void setAlergias(String alergias) {
		this.alergias = alergias;
	}

	public String getObs() {
		return this.obs;
	}

	public void setObs(String obs) {
		this.obs = obs;
	}

	public String getMotivo() {
		return this.motivo;
	}

	public void setMotivo(String motivo) {
		this.motivo = motivo;
	}

	public Set<Ficha> getFichas() {
		return this.fichas;
	}

	public void setFichas(Set<Ficha> fichas) {
		this.fichas = fichas;
	}
	

}
