package br.com.clinica.entity;


// Generated 26/03/2011 00:27:00 by Hibernate Tools 3.2.4.GA

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Exfezes generated by hbm2java
 */
@Entity
@Table(name = "exfezes", schema = "public")
public class Exfezes implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5640359700194837458L;
	private int codexfezes;
	private Ficha ficha;
	private Date dtregistro;
	private String resultado;
	private String metodo;

	public Exfezes() {
	}

	public Exfezes(int codexfezes, Ficha ficha) {
		this.codexfezes = codexfezes;
		this.ficha = ficha;
	}

	public Exfezes(int codexfezes, Ficha ficha, Date dtregistro,
			String resultado, String metodo) {
		this.codexfezes = codexfezes;
		this.ficha = ficha;
		this.dtregistro = dtregistro;
		this.resultado = resultado;
		this.metodo = metodo;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE,generator = "id_fezes")
	@SequenceGenerator( name = "id_fezes", sequenceName = "id_fezes")
	@Column(name = "codexfezes", unique = true, nullable = false)
	public int getCodexfezes() {
		return this.codexfezes;
	}
	public void setCodexfezes(int codexfezes) {
		this.codexfezes = codexfezes;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codficha", nullable = false)
	@NotNull
	public Ficha getFicha() {
		return this.ficha;
	}

	public void setFicha(Ficha ficha) {
		this.ficha = ficha;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dtregistro", length = 13)
	public Date getDtregistro() {
		return this.dtregistro;
	}

	public void setDtregistro(Date dtregistro) {
		this.dtregistro = dtregistro;
	}

	@Column(name = "resultado", length = 50)
	@Length(max = 50)
	public String getResultado() {
		return this.resultado;
	}

	public void setResultado(String resultado) {
		this.resultado = resultado;
	}

	@Column(name = "metodo", length = 50)
	@Length(max = 50)
	public String getMetodo() {
		return this.metodo;
	}

	public void setMetodo(String metodo) {
		this.metodo = metodo;
	}

}
