package br.com.clinica.entity;

// Generated 26/03/2011 00:27:00 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.validator.Length;

/**
 * Internacao generated by hbm2java
 */
@Entity
@Table(name = "internacao", schema = "public")
public class Internacao implements java.io.Serializable {
	private static final long serialVersionUID = 462216157723572319L;
	private int codinternacao;
	private Ficha ficha;
	private String obs;
	private Date dtregistro;
	private Date estsaida;
	private Date datasaida;
	private Float vlcheque;
	private Date datahorasaida;
	private String motivosaida;
	private String obssaida;
	private Set<InternacaoMedicamento> internacaoMedicamentos = new HashSet<InternacaoMedicamento>(
			0);

	public Internacao() {
	}

	public Internacao(int codinternacao) {
		this.codinternacao = codinternacao;
	}

	public Internacao(int codinternacao, Ficha ficha, String obs,
			Date dtregistro, Date estsaida, Date datasaida, Float vlcheque,
			Date datahorasaida, String motivosaida, String obssaida,
			Set<InternacaoMedicamento> internacaoMedicamentos) {
		this.codinternacao = codinternacao;
		this.ficha = ficha;
		this.obs = obs;
		this.dtregistro = dtregistro;
		this.estsaida = estsaida;
		this.datasaida = datasaida;
		this.vlcheque = vlcheque;
		this.datahorasaida = datahorasaida;
		this.motivosaida = motivosaida;
		this.obssaida = obssaida;
		this.internacaoMedicamentos = internacaoMedicamentos;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE,generator = "id_interna")
	@SequenceGenerator( name = "id_interna", sequenceName = "id_interna")
	@Column(name = "codinternacao", unique = true, nullable = false)
	public int getCodinternacao() {
		return this.codinternacao;
	}
	public void setCodinternacao(int codinternacao) {
		this.codinternacao = codinternacao;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codficha")
	public Ficha getFicha() {
		return this.ficha;
	}

	public void setFicha(Ficha ficha) {
		this.ficha = ficha;
	}

	@Column(name = "obs")
	public String getObs() {
		return this.obs;
	}

	public void setObs(String obs) {
		this.obs = obs;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dtregistro", length = 13)
	public Date getDtregistro() {
		return this.dtregistro;
	}

	public void setDtregistro(Date dtregistro) {
		this.dtregistro = dtregistro;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "estsaida", length = 13)
	public Date getEstsaida() {
		return this.estsaida;
	}

	public void setEstsaida(Date estsaida) {
		this.estsaida = estsaida;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "datasaida", length = 13)
	public Date getDatasaida() {
		return this.datasaida;
	}

	public void setDatasaida(Date datasaida) {
		this.datasaida = datasaida;
	}

	@Column(name = "vlcheque", precision = 8, scale = 8)
	public Float getVlcheque() {
		return this.vlcheque;
	}

	public void setVlcheque(Float vlcheque) {
		this.vlcheque = vlcheque;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "datahorasaida", length = 13)
	public Date getDatahorasaida() {
		return this.datahorasaida;
	}

	public void setDatahorasaida(Date datahorasaida) {
		this.datahorasaida = datahorasaida;
	}

	@Column(name = "motivosaida", length = 50)
	@Length(max = 50)
	public String getMotivosaida() {
		return this.motivosaida;
	}

	public void setMotivosaida(String motivosaida) {
		this.motivosaida = motivosaida;
	}

	@Column(name = "obssaida")
	public String getObssaida() {
		return this.obssaida;
	}

	public void setObssaida(String obssaida) {
		this.obssaida = obssaida;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "internacao")
	public Set<InternacaoMedicamento> getInternacaoMedicamentos() {
		return this.internacaoMedicamentos;
	}

	public void setInternacaoMedicamentos(
			Set<InternacaoMedicamento> internacaoMedicamentos) {
		this.internacaoMedicamentos = internacaoMedicamentos;
	}

}
