package br.com.clinica.entity;

// Generated 26/03/2011 00:27:00 by Hibernate Tools 3.2.4.GA

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * InternacaoMedicamento generated by hbm2java
 */
@Entity
@Table(name = "internacao_medicamento", schema = "public")
public class InternacaoMedicamento implements java.io.Serializable {
	private static final long serialVersionUID = 462216157723572319L;
	private int codinternacaoMedicamento;
	private Internacao internacao;
	private String medicamento;
	private Integer doses;
	private String forma;
	private Integer qtd;
	private Integer dias;
	private Date horarios;

	public InternacaoMedicamento() {
	}

	public InternacaoMedicamento(int codinternacaoMedicamento) {
		this.codinternacaoMedicamento = codinternacaoMedicamento;
	}

	public InternacaoMedicamento(int codinternacaoMedicamento,
			Internacao internacao, String medicamento, Integer doses,
			String forma, Integer qtd, Integer dias, Date horarios) {
		this.codinternacaoMedicamento = codinternacaoMedicamento;
		this.internacao = internacao;
		this.medicamento = medicamento;
		this.doses = doses;
		this.forma = forma;
		this.qtd = qtd;
		this.dias = dias;
		this.horarios = horarios;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE,generator = "id_medicamento")
	@SequenceGenerator( name = "id_medicamento", sequenceName = "id_medicamento")
	@Column(name = "codinternacao_medicamento", unique = true, nullable = false)
	public int getCodinternacaoMedicamento() {
		return this.codinternacaoMedicamento;
	}
	public void setCodinternacaoMedicamento(int codinternacaoMedicamento) {
		this.codinternacaoMedicamento = codinternacaoMedicamento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codinternacao")
	public Internacao getInternacao() {
		return this.internacao;
	}

	public void setInternacao(Internacao internacao) {
		this.internacao = internacao;
	}

	@Column(name = "medicamento")
	public String getMedicamento() {
		return this.medicamento;
	}

	public void setMedicamento(String medicamento) {
		this.medicamento = medicamento;
	}

	@Column(name = "doses")
	public Integer getDoses() {
		return this.doses;
	}

	public void setDoses(Integer doses) {
		this.doses = doses;
	}

	@Column(name = "forma")
	public String getForma() {
		return this.forma;
	}

	public void setForma(String forma) {
		this.forma = forma;
	}

	@Column(name = "qtd")
	public Integer getQtd() {
		return this.qtd;
	}

	public void setQtd(Integer qtd) {
		this.qtd = qtd;
	}

	@Column(name = "dias")
	public Integer getDias() {
		return this.dias;
	}

	public void setDias(Integer dias) {
		this.dias = dias;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "horarios", length = 15)
	public Date getHorarios() {
		return this.horarios;
	}

	public void setHorarios(Date horarios) {
		this.horarios = horarios;
	}

}
