package br.com.clinica.entity;

// Generated 26/03/2011 00:27:00 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.validator.Length;

/**
 * Tiporetornovacinacao generated by hbm2java
 */
@Entity
@Table(name = "tiporetornovacinacao", schema = "public")
public class Tiporetornovacinacao implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4846227205361011037L;
	private int codtiporetornovacinacao;
	private String retorno;
	private Integer dias;
	private Set<Vacina> vacinas = new HashSet<Vacina>(0);

	public Tiporetornovacinacao() {
	}

	public Tiporetornovacinacao(int codtiporetornovacinacao) {
		this.codtiporetornovacinacao = codtiporetornovacinacao;
	}

	public Tiporetornovacinacao(int codtiporetornovacinacao, String retorno,
			Integer dias, Set<Vacina> vacinas) {
		this.codtiporetornovacinacao = codtiporetornovacinacao;
		this.retorno = retorno;
		this.dias = dias;
		this.vacinas = vacinas;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE,generator = "id_retorno")
	@SequenceGenerator( name = "id_retorno", sequenceName = "id_retorno")
	@Column(name = "codtiporetornovacinacao", unique = true, nullable = false)
	public int getCodtiporetornovacinacao() {
		return this.codtiporetornovacinacao;
	}

	public void setCodtiporetornovacinacao(int codtiporetornovacinacao) {
		this.codtiporetornovacinacao = codtiporetornovacinacao;
	}

	@Column(name = "retorno", length = 50)
	@Length(max = 50)
	public String getRetorno() {
		return this.retorno;
	}

	public void setRetorno(String retorno) {
		this.retorno = retorno;
	}

	@Column(name = "dias")
	public Integer getDias() {
		return this.dias;
	}

	public void setDias(Integer dias) {
		this.dias = dias;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tiporetornovacinacao")
	public Set<Vacina> getVacinas() {
		return this.vacinas;
	}

	public void setVacinas(Set<Vacina> vacinas) {
		this.vacinas = vacinas;
	}

}
