package br.com.clinica.entity;

// Generated 26/03/2011 00:27:00 by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Vacina generated by hbm2java
 */
@Entity
@Table(name = "vacina", schema = "public")
public class Vacina implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int codvacinas;
	private Vacinacao vacinacao;
	private Tiporetornovacinacao tiporetornovacinacao;
	private String nomevacina;
	private Integer retorno;
	private Integer doses;
	private Integer proximavacina;

	public Vacina() {
	}

	public Vacina(int codvacinas, Vacinacao vacinacao) {
		this.codvacinas = codvacinas;
		this.vacinacao = vacinacao;
	}

	public Vacina(int codvacinas, Vacinacao vacinacao,
			Tiporetornovacinacao tiporetornovacinacao, String nomevacina,
			Integer retorno, Integer doses, Integer proximavacina) {
		this.codvacinas = codvacinas;
		this.vacinacao = vacinacao;
		this.tiporetornovacinacao = tiporetornovacinacao;
		this.nomevacina = nomevacina;
		this.retorno = retorno;
		this.doses = doses;
		this.proximavacina = proximavacina;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE,generator = "id_vacina")
	@SequenceGenerator( name = "id_vacina", sequenceName = "id_vacina")
	@Column(name = "codvacinas", unique = true, nullable = false)
	public int getCodvacinas() {
		return this.codvacinas;
	}

	public void setCodvacinas(int codvacinas) {
		this.codvacinas = codvacinas;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codvacinacao", nullable = false)
	@NotNull
	public Vacinacao getVacinacao() {
		return this.vacinacao;
	}

	public void setVacinacao(Vacinacao vacinacao) {
		this.vacinacao = vacinacao;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codtiporetornovacinacao")
	public Tiporetornovacinacao getTiporetornovacinacao() {
		return this.tiporetornovacinacao;
	}

	public void setTiporetornovacinacao(
			Tiporetornovacinacao tiporetornovacinacao) {
		this.tiporetornovacinacao = tiporetornovacinacao;
	}

	@Column(name = "nomevacina", length = 40)
	@Length(max = 40)
	public String getNomevacina() {
		return this.nomevacina;
	}

	public void setNomevacina(String nomevacina) {
		this.nomevacina = nomevacina;
	}

	@Column(name = "retorno")
	public Integer getRetorno() {
		return this.retorno;
	}

	public void setRetorno(Integer retorno) {
		this.retorno = retorno;
	}

	@Column(name = "doses")
	public Integer getDoses() {
		return this.doses;
	}

	public void setDoses(Integer doses) {
		this.doses = doses;
	}

	@Column(name = "proximavacina")
	public Integer getProximavacina() {
		return this.proximavacina;
	}

	public void setProximavacina(Integer proximavacina) {
		this.proximavacina = proximavacina;
	}

}
