package br.com.clinica.entity;

// Generated 26/03/2011 00:27:00 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Vacinacao generated by hbm2java
 */
@Entity
@Table(name = "vacinacao", schema = "public")
public class Vacinacao implements java.io.Serializable {

	private int codvacinacao;
	private Ficha ficha;
	private String nomelaboratorio;
	private Date dtvacinacao;
	private String lote;
	private boolean retornou;
	private Set<Vacina> vacinas = new HashSet<Vacina>(0);

	public Vacinacao() {
	}

	public Vacinacao(int codvacinacao, Ficha ficha, boolean retornou) {
		this.codvacinacao = codvacinacao;
		this.ficha = ficha;
		this.retornou = retornou;
	}

	public Vacinacao(int codvacinacao, Ficha ficha, String nomelaboratorio,
			Date dtvacinacao, String lote, boolean retornou, Set<Vacina> vacinas) {
		this.codvacinacao = codvacinacao;
		this.ficha = ficha;
		this.nomelaboratorio = nomelaboratorio;
		this.dtvacinacao = dtvacinacao;
		this.lote = lote;
		this.retornou = retornou;
		this.vacinas = vacinas;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE,generator = "id_vacao")
	@SequenceGenerator( name = "id_vacao", sequenceName = "id_vacao")
	@Column(name = "codvacinacao", unique = true, nullable = false)
	public int getCodvacinacao() {
		return this.codvacinacao;
	}

	public void setCodvacinacao(int codvacinacao) {
		this.codvacinacao = codvacinacao;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codficha", nullable = false)
	@NotNull
	public Ficha getFicha() {
		return this.ficha;
	}

	public void setFicha(Ficha ficha) {
		this.ficha = ficha;
	}

	@Column(name = "nomelaboratorio", length = 30)
	@Length(max = 30)
	public String getNomelaboratorio() {
		return this.nomelaboratorio;
	}

	public void setNomelaboratorio(String nomelaboratorio) {
		this.nomelaboratorio = nomelaboratorio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dtvacinacao", length = 13)
	public Date getDtvacinacao() {
		return this.dtvacinacao;
	}

	public void setDtvacinacao(Date dtvacinacao) {
		this.dtvacinacao = dtvacinacao;
	}

	@Column(name = "lote")
	public String getLote() {
		return this.lote;
	}

	public void setLote(String lote) {
		this.lote = lote;
	}

	@Column(name = "retornou", nullable = false)
	public boolean isRetornou() {
		return this.retornou;
	}

	public void setRetornou(boolean retornou) {
		this.retornou = retornou;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vacinacao")
	public Set<Vacina> getVacinas() {
		return this.vacinas;
	}

	public void setVacinas(Set<Vacina> vacinas) {
		this.vacinas = vacinas;
	}

}
